robud/robud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from robud_website import views as robud_website_views

from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('robud_website.urls', namespace='robud_website')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

robud/robud_website/urls.py
#_*_coding:utf-8_*_
from django.conf.urls import url,include
from django.contrib import admin
from  . import views
from robud_website import views as website_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', website_views.index, name='index'),
    url(r'aboutus/$', website_views.aboutus_story, name='aboutus_story'),
    url(r'aboutusteam/$', website_views.aboutus_team, name='aboutus_team'),
    url(r'aboutuspromise/$', website_views.aboutus_promise, name='aboutus_promise'),
    url(r'purchasechannels/$', website_views.purchasechannels, name='purchasechannels'),
    url(r'contact/$', website_views.contact, name='contact'),
    url(r'products/$', website_views.products, name='products'),
    url(r'products/(?P<key>[a-zA-Z]+)/(?P<id>\d+)', website_views.products, name='products'),
    url(r'get_labels/$', website_views.get_labels, name='get_labels'),
    url(r'news_index/$', website_views.news_index, name='news_index'),
    url(r'video_index/(?P<id>\d+)?', website_views.video_index, name='video_index'),
    url(r'customer_work/$', website_views.customer_work, name='customer_work'),
    url(r'like/$', website_views.like, name='like'),
    url(r'get_artists_work/$', website_views.get_artists_work, name='get_artists_work'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robud/robud_website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class ApplyAge(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=120)

    class Meta:
        verbose_name = '产品适用年龄'
        verbose_name_plural = "产品适用年龄"

    def __unicode__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=120)

    class Meta:
        verbose_name = '产品品种'
        verbose_name_plural = "产品品种"

    def __unicode__(self):
        return self.name


class SecondTitle(models.Model):
    name = models.CharField(max_length=120)

    class Meta:
        verbose_name = '二级标题'
        verbose_name_plural = "二级标题"

    def __unicode__(self):
        return self.name


class RobudProduct(models.Model):
    category_id = models.ForeignKey(Category, null=True, verbose_name='所属品种')
    age_id = models.ForeignKey(ApplyAge, null=True, verbose_name='适用年龄')
    title_id = models.ForeignKey(SecondTitle, null=True, verbose_name='二级标题')
    name = models.CharField(max_length=120, verbose_name='产品名')
    size = models.CharField(max_length=120, null=True, blank=True, verbose_name='组装尺寸')
    pack_size = models.CharField(max_length=120, null=True, blank=True, verbose_name='包装尺寸')
    wood_qty = models.IntegerField(null=True, blank=True, verbose_name='木片数量')
    image = models.ImageField(blank=True, upload_to='products_images/%Y%m%d', verbose_name='产品图')

    class Meta:
        verbose_name = '所有产品'
        verbose_name_plural = "所有产品"

    def __unicode__(self):
        return self.name


class VideoType(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=120)

    class Meta:
        verbose_name = '视频所属类型'
        verbose_name_plural = "视频所属的类型、分类"

    def __unicode__(self):
        return self.name


class Videos(models.Model):
    name = models.CharField(max_length=120, verbose_name='视频名字')
    type_id = models.ForeignKey(VideoType, null=True, verbose_name='所属品种')
    video = models.FileField(blank=True, upload_to='videos/%Y%m%d', verbose_name='视频')
    image = models.ImageField(blank=True, upload_to='video_cover/%Y%m%d', verbose_name='视频表层图')

    class Meta:
        verbose_name = '所有视频'
        verbose_name_plural = "所有视频"

    def __unicode__(self):
        return self.name


class IpSet(models.Model):
    ip_number = models.GenericIPAddressField()

    def __unicode__(self):
        return self.ip_number


class CustomerWorkType(models.Model):
    name = models.CharField(max_length=120, verbose_name='小艺术家作品类型')

    class Meta:
        verbose_name = '小艺术家作品类型'
        verbose_name_plural = "小艺术家作品类型"

    def __unicode__(self):
        return self.name


class CustomerWork(models.Model):
    Month = (
        (1, u'1月'),
        (2, u'2月'),
        (3, u'3月'),
        (4, u'4月'),
        (5, u'5月'),
        (6, u'6月'),
        (7, u'7月'),
        (8, u'8月'),
        (9, u'9月'),
        (10, u'10月'),
        (11, u'11月'),
        (12, u'12月'),
    )
    author = models.CharField(max_length=120, verbose_name='作者')
    age = models.CharField(max_length=120, verbose_name='作者年龄')
    name = models.CharField(max_length=120, verbose_name='作品名字')
    type_id = models.ForeignKey(CustomerWorkType, null=True, verbose_name='作品类型')
    month = models.IntegerField(verbose_name='月份', choices=Month)
    like_ips = models.ManyToManyField(IpSet, verbose_name='点赞ip', blank=True,)
    image = models.ImageField(blank=True, upload_to='customer_work/%Y%m%d', verbose_name='小艺术家作品')

    class Meta:
        verbose_name = '小艺术家作品'
        verbose_name_plural = "小艺术家作品"

    def __unicode__(self):
        return self.name

robud/robud_website/views.py
# -*- coding: utf-8 -*-
import json

from django.db.models import QuerySet, Sum, Count
from django.http import HttpResponse
from django.shortcuts import render,redirect

# Create your views here.
from django.shortcuts import render
import smtplib
from email.mime.text import MIMEText
from email.header import Header
from django.views.decorators.csrf import csrf_exempt
from robud_website.models import ApplyAge, Category, RobudProduct, VideoType, Videos, CustomerWorkType, CustomerWork, IpSet, SecondTitle


def index(request):
    return render(request, 'robud_website/index.html')


def aboutus_story(request):
    return render(request, 'robud_website/aboutus.html',{'scroll':False})


def aboutus_team(request):
    return render(request, 'robud_website/aboutus.html',{'scroll':True, 'top':json.dumps(['850'])})


def aboutus_promise(request):
    return render(request, 'robud_website/aboutus.html',{'scroll':True, 'top':json.dumps(['2500'])})


def purchasechannels(request):
    return render(request, 'robud_website/purchasechannels.html')


def news_index(request):
    return render(request, 'robud_website/news_index.html')


# 小小艺术家
def customer_work(request):
    # 获取访问者的ip
    if request.META.has_key('HTTP_X_FORWARDED_FOR'):
        ip = request.META['HTTP_X_FORWARDED_FOR']
    else:
        ip = request.META['REMOTE_ADDR']

    data = {}
    arr = []
    # 获取作品分类名
    for i in CustomerWorkType.objects.all():
        arr.append({
            'id': i.id,
            'name': i.name
        })
    data['cate'] = arr
    data['month'] = CustomerWork.Month
    arr = []
    for i in CustomerWork.objects.filter(type_id=1):
        arr.append({
            'image': i.image.url,
            'likes': i.like_ips.count(),   # 点赞数
            'author': i.author,
            'age': i.age,
            'id': i.id,
            'visitor_like': True if i.like_ips.filter(ip_number=ip) else False
        })
    data['images'] = arr
    return render(request, 'robud_website/customer_work.html', data)


# 点赞
@csrf_exempt
def like(request):
    like_id = request.POST['id']
    if request.META.has_key('HTTP_X_FORWARDED_FOR'):
        ip = request.META['HTTP_X_FORWARDED_FOR']
    else:
        ip = request.META['REMOTE_ADDR']
    # 判断此ip是否已存在于数据库中,若不在，把ip加入到数据库，并直接点赞，
    # 若在，判断此图是否被此ip点赞过,若点过，则取消点赞，若没有，则点赞
    if IpSet.objects.filter(ip_number=ip):
        like_work = CustomerWork.objects.get(id=like_id)
        user_ip = IpSet.objects.get(ip_number=ip)
        if user_ip in like_work.like_ips.all():
            like_work.like_ips.remove(user_ip)
            print 'dianguo quxiao'
        else:
            like_work.like_ips.add(user_ip)
            like_work.save()
            print 'meidian zan'
    else:
        new_ip = IpSet()
        new_ip.ip_number = ip
        new_ip.save()
        like_work = CustomerWork.objects.get(id=like_id)
        like_work.like_ips.add(new_ip)
        like_work.save()
        print 'first dian'

    like_work = CustomerWork.objects.get(id=like_id)
    data = {
        'likes': like_work.like_ips.count(),  # 点赞数
        'id': like_work.id,
        'visitor_like': True if like_work.like_ips.filter(ip_number=ip) else False
    }
    return HttpResponse(json.dumps(data), content_type='application/json')


# 小小艺术家 点击分类获取图片
@csrf_exempt
def get_artists_work(request):
    type = request.GET['type']
    month = request.GET.get('month')
    results = CustomerWork.objects.filter(type_id=type)
    if month:
        results = results.filter(month=month)
    if request.META.has_key('HTTP_X_FORWARDED_FOR'):
        ip = request.META['HTTP_X_FORWARDED_FOR']
    else:
        ip = request.META['REMOTE_ADDR']
    arr = []
    data = {}
    for i in results:
        arr.append({
            'image': i.image.url,
            'likes': i.like_ips.count(),   # 点赞数
            'author': i.author,
            'age': i.age,
            'id': i.id,
            'visitor_like': True if i.like_ips.filter(ip_number=ip) else False
        })
    data['images'] = arr
    return HttpResponse(json.dumps(data), content_type='application/json')


def video_index(request, id=None):
    data = {}
    arr = []
    # 视频分类的获取
    for i in VideoType.objects.all():
        arr.append({
            'id': i.id,
            'name': i.name
        })
    data['video_type'] = arr
    if id:
        videos = Videos.objects.filter(type_id=id)
    else:
        videos = Videos.objects.filter(type_id=1)
    data['videos'] = videos
    return render(request, 'robud_website/video_index.html', data)


def contact(request):
    return render(request, 'robud_website/contact.html')


def products(request, key=None, id=None):
    print key, id
    data = {}
    arr = []
    # label数据获取
    for i in ApplyAge.objects.all():
        arr.append({
            'id':i.id,
            'name':i.name,
            'type':'age'
        })
    data['label_age'] = arr
    arr = []
    for i in Category.objects.all():
        arr.append({
            'id': i.id,
            'name': i.name,
            'type': 'category'
        })
    data['label_category'] = arr
    if key and id:
        if key == 'age':
            products = RobudProduct.objects.filter(age_id=id)
        else:
            products = RobudProduct.objects.filter(category_id=id)
    else:
        products = RobudProduct.objects.filter(category_id=Category.objects.all()[0].id)
    query = products.values_list('title_id').annotate(s_count=Count('id'))

    a = []
    for i in query:
        results = {
            'name': SecondTitle.objects.get(id=i[0]).name,
            'images': products.filter(title_id=i[0])
        }
        a.append(results)
    data['products'] = a
    # print json.dumps(data, sort_keys=True, indent=4, separators=(',', ': '), encoding="utf-8", ensure_ascii=False)
    return render(request, 'robud_website/products.html', data)


# 获取labels
def get_labels(request):
    data = {}
    arr = []
    for i in ApplyAge.objects.all():
        arr.append({
            'id':i.id,
            'name':i.name,
            'type':'age'
        })
    data['label_age'] = arr
    arr = []
    for i in Category.objects.all():
        arr.append({
            'id': i.id,
            'name': i.name,
            'type': 'category'
        })
    data['label_category'] = arr
    arr = []
    for i in VideoType.objects.all():
        arr.append({
            'id': i.id,
            'name': i.name
        })
    data['video_type'] = arr
    return HttpResponse(json.dumps(data), content_type='application/json')

robud/robud_website/templates/robud_website/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper-3.4.1.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/base/favicon.png' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <div id="rb_head_container">
        <div class="black_line_wrap">

        </div>
        <div class="container_fluid nav_container">
            <div class="nav_link_wrap">
                <div>
                    <a href="{% url 'robud_website:index' %}"><img class="base_logo" src="{% static 'images/base/logo_03.png' %}" alt=""></a>
                </div>
                <div class="nav_item1 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon1.png' %}" alt=""><p>一起来玩</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li>根据年龄</li>
                            <li><a href="">01-03</a></li>
                            <li><a href="">03-06</a></li>
                            <li><a href="">06-08</a></li>
                        </ul>
                        <ul>
                            <li>根据品种</li>
                            <li><a href="">绘画</a></li>
                            <li><a href="">黏土</a></li>
                            <li><a href="">贴纸</a></li>
                            <li><a href="">拼图</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item2 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon2.png' %}" alt=""><p>最新资讯</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">新品上市</a></li>
                            <li><a href="">活动资讯</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item3 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon3.png' %}" alt=""><p>视频教程</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">涂色</a></li>
                            <li><a href="">粘土</a></li>
                            <li><a href="">育儿讲座</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item4 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon4.png' %}" alt=""><p>小艺术家</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">绘画作品</a></li>
                            <li><a href="">粘土作品</a></li>
                            <li><a href="">往期回顾</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item5 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon5.png' %}" alt=""><p>关于若小贝</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="{% url 'robud_website:aboutus_story' %}">我们的故事</a></li>
                            <li><a href="{% url 'robud_website:aboutus_team' %}">我们的团队</a></li>
                            <li><a href="{% url 'robud_website:aboutus_promise' %}">我们的承诺</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item6 nav_item_wrap">
                    <a href="{% url 'robud_website:purchasechannels' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon6.png' %}" alt=""><p>购买渠道</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">天猫旗舰店</a></li>
                            <li><a href="">京东旗舰店</a></li>
                            <li><a href="">线下合作商</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item7 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon7.png' %}" alt=""><p>联系我们</p></a>
                </div>
            </div>
{#            下拉框#}
{#            <div class="nav_drap_down">#}
{#                <div class="">#}
{#                    #}
{#                </div>#}
{#            </div>#}
        </div>
        <div class="dropdown_bg">

        </div>
    </div>

    {% block main_content %}{% endblock %}

    <div id="rb_foot_container" class="container_fluid">
        <div class="footer_line"></div>
        <div class="footer_mainwrap">
            <div class="col-md-8 col-md-offset-2 foot_wrap col-sm-12">
                <div class="col-md-3 col-sm-3">
                    <img src="{% static 'images/base/logo_03.png' %}" alt="">
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>根据年龄</li>
                        <li><a href="">1-3</a></li>
                        <li><a href="">3-6</a></li>
                        <li><a href="">6-8</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>关于若小贝</li>
                        <li><a href="">我们的故事</a></li>
                        <li><a href="">我们的团队</a></li>
                        <li><a href="">安全认证</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>联系我们</li>
                        <li><a href="">mark.wang@robotime.com</a></li>
                        <li><a href="">中国江苏省苏州工业园区星汉街5号C幢三楼305室</a></li>
                        <li><a href="">备案号：6658421352321115</a></li>
                        <li>400-710-8099</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>购买渠道</li>
                        <li><a href="">天猫旗舰店</a></li>
                        <li><a href="">京东旗舰店</a></li>
                        <li><a href="">线下合作</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>根据品类</li>
                        <li><a href="">绘画</a></li>
                        <li><a href="">粘土</a></li>
                        <li><a href="">贴纸</a></li>
                        <li><a href="">拼图</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>购买渠道</li>
                        <li><a href="">天猫旗舰店</a></li>
                        <li><a href="">京东旗舰店</a></li>
                        <li><a href="">线下合作</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-md-offset-2" style="color: white;margin-top: 50px;margin-bottom: 10px">Copyright 2008-2017 © Robud. All Right Reserved</div>
        </div>
    </div>

</body>
<script src="{% static 'js/jquery-3.0.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/swiper-3.4.1.jquery.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
{% block js %}{% endblock %}
</html>

robud/robud_website/templates/robud_website/base_new.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base_new.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper-3.4.1.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/base/favicon.png' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <div id="rb_head_container">
        <div class="black_line_wrap">

        </div>
        <div class="container-fluid nav_container">
            <div class="sssss">
                <span><img src="{% static 'images/base/bar.png' %}" alt=""></span>
            </div>
            <div class="nav_link_wrap">
                <div>
                    <a href="{% url 'robud_website:index' %}"><img class="base_logo" src="{% static 'images/base/logo_03.png' %}" alt=""></a>
                </div>
                <div class="nav_item1 nav_item_wrap">
                    <a href="{% url 'robud_website:products' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon1.png' %}" alt=""><p>一起来玩</p></a>
                    <div class="nav_dropdown">
                        <ul class="divi_by_age">
                            <li>根据年龄</li>
                        </ul>
                        <ul class="divi_by_cate">
                            <li>根据品种</li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item2 nav_item_wrap">
                    <a href="{% url 'robud_website:news_index' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon2.png' %}" alt=""><p>最新资讯</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">新品上市</a></li>
                            <li><a href="">活动资讯</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item3 nav_item_wrap">
                    <a href="{% url 'robud_website:video_index' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon3.png' %}" alt=""><p>视频教程</p></a>
                    <div class="nav_dropdown">
                        <ul class="divi_by_videotype">
                            <li style="display: none">xx</li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item4 nav_item_wrap">
                    <a href="{% url 'robud_website:customer_work' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon4.png' %}" alt=""><p>小艺术家</p></a>
{#                    <div class="nav_dropdown">#}
{#                        <ul>#}
{#                            <li style="display: none">xx</li>#}
{#                            <li><a href="">绘画作品</a></li>#}
{#                            <li><a href="">粘土作品</a></li>#}
{#                            <li><a href="">往期回顾</a></li>#}
{#                        </ul>#}
{#                    </div>#}
                </div>
                <div class="nav_item5 nav_item_wrap">
                    <a href=""><img class="nav_icon" src="{% static 'images/base/nav_icon5.png' %}" alt=""><p>关于若小贝</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="{% url 'robud_website:aboutus_story' %}">我们的故事</a></li>
                            <li><a href="{% url 'robud_website:aboutus_team' %}">我们的团队</a></li>
                            <li><a href="{% url 'robud_website:aboutus_promise' %}">我们的承诺</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item6 nav_item_wrap">
                    <a href="{% url 'robud_website:purchasechannels' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon6.png' %}" alt=""><p>购买渠道</p></a>
                    <div class="nav_dropdown">
                        <ul>
                            <li style="display: none">xx</li>
                            <li><a href="">天猫旗舰店</a></li>
                            <li><a href="">京东旗舰店</a></li>
                            <li><a href="">线下合作商</a></li>
                        </ul>
                    </div>
                </div>
                <div class="nav_item7 nav_item_wrap">
                    <a href="{% url 'robud_website:contact' %}"><img class="nav_icon" src="{% static 'images/base/nav_icon7.png' %}" alt=""><p>联系我们</p></a>
                </div>
            </div>
{#            下拉框#}
{#            <div class="nav_drap_down">#}
{#                <div class="">#}
{#                    #}
{#                </div>#}
{#            </div>#}
        </div>
        <div class="dropdown_bg">

        </div>
    </div>

    {% block main_content %}{% endblock %}

    <div id="rb_foot_container" class="container_fluid">
        <div class="footer_line"></div>
        <div class="footer_mainwrap">
            <div class="col-md-8 col-md-offset-2 foot_wrap col-sm-12">
                <div class="col-md-3 col-sm-3">
                    <img src="{% static 'images/base/logo_03.png' %}" alt="">
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>根据年龄</li>
                        <li><a href="">1-3</a></li>
                        <li><a href="">3-6</a></li>
                        <li><a href="">6-8</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>关于若小贝</li>
                        <li><a href="">我们的故事</a></li>
                        <li><a href="">我们的团队</a></li>
                        <li><a href="">安全认证</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>联系我们</li>
                        <li><a href="">mark.wang@robotime.com</a></li>
                        <li><a href="">中国江苏省苏州工业园区星汉街5号C幢三楼305室</a></li>
                        <li><a href="">备案号：6658421352321115</a></li>
                        <li>400-710-8099</li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>购买渠道</li>
                        <li><a href="">天猫旗舰店</a></li>
                        <li><a href="">京东旗舰店</a></li>
                        <li><a href="">线下合作</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>根据品类</li>
                        <li><a href="">绘画</a></li>
                        <li><a href="">粘土</a></li>
                        <li><a href="">贴纸</a></li>
                        <li><a href="">拼图</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <ul>
                        <li>购买渠道</li>
                        <li><a href="">天猫旗舰店</a></li>
                        <li><a href="">京东旗舰店</a></li>
                        <li><a href="">线下合作</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-md-offset-2" style="color: white;margin-top: 50px;margin-bottom: 10px">Copyright 2008-2017 © Robud. All Right Reserved</div>
        </div>
    </div>

</body>
<script src="{% static 'js/jquery-3.0.0.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/swiper-3.4.1.jquery.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/base.js' %}" type="text/javascript" charset="utf-8"></script>
{% block js %}{% endblock %}
</html>

robud/robud_website/templates/robud_website/video_index.html
{% extends "robud_website/base_new.html" %}
{% load staticfiles %}
{% block title %}视频教程{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/video-js.css' %}">
{% endblock %}


{% block main_content %}

    <div class="container_fluid video_index_page">
        <div class="col-md-8 col-md-offset-2">
            <div class="video_index_top">
                <img src="{% static 'images/somepages/video_index_top.png' %}" alt="">
                <p>XXXXXXXX</p>
                <div class="video_type_wrap">
                    {% for i in video_type %}
                        <span><a href="{% url 'robud_website:video_index' i.id  %}">{{ i.name }}</a></span>
                    {% endfor %}

                </div>
            </div>

            <div class="video_container">
                {% for i in videos %}
                    <div class="video_item">
                        <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="320" height="264"
                          data-setup="{}" poster="{{ i.image.url }}">
                           <source src="{{ i.video.url }}" type='video/mp4' />
                        </video>
                    </div>
                {% endfor %}
{#                <div class="video_item">#}
{#                    <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="320" height="264"#}
{#                      data-setup="{}" poster="{% static 'images/news_index/3_03.jpg' %}">#}
{#                       <source src="{% static 'video/index.mp4' %}" type='video/mp4' />#}
{#                    </video>#}
{#                </div>#}
            </div>
        </div>
    </div>

{#    <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264"#}
{#      data-setup="{}" poster="{% static 'images/news_index/3_03.jpg' %}">#}
{#       <source src="{% static 'video/index.mp4' %}" type='video/mp4' />#}
{#    </video>#}

{% endblock %}


{% block js %}
    <script src="{% static 'js/video.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}